Import('*')
import numpy as np

target = []
for subset_year in np.arange(2011, 2024, 1):
    for subset_month in np.arange(1, 13, 1):
        if (subset_year != 2023) or (subset_year == 2023 and subset_month < 9):
            for subset_data_name in ['create_data', 'delete_data', 'fork_data', 'issue_comment_data', 'issue_data','pull_request_data',
                                     'pull_request_review_comment_data', 'pull_request_review_data', 'push_data', 'release_data', 'watch_data']:
                target = target.append(f'#drive/output/scrape/extract_github_data/{subset_data_name}/{subset_data_name.replace('_data','')}_{subset_year}_{subset_month}.csv')

source = ['#source/scrape/extract_github_data/docs/query_github_data.py',
          '#output/derived/collect_github_repos/linked_pypi_github.csv']

env.Python(target, source)
