import os


target = ['drive/output/derived/filter_nonunique_push/non_unique_push_complete.csv']
source = []
for file in os.listdir('../../../drive/output/scrape/push_pr_commit_data/pull_request_data/'):
    source.append(f'#drive/output/scrape/push_pr_commit_data/pull_request_data/{file}')
for file in os.listdir('../../../drive/output/scrape/push_pr_commit_data/push_data/'):
    source.append(f'#drive/output/scrape/push_pr_commit_data/push_data/{file}')
source.append(f'#source/derived/filter_nonunique_push/get_unique_push.py')

env.Python(target, source)