Import('*')

import os
import glob

target = ['#drive/output/derived/filter_nonunique_push/non_unique_push_complete.csv']

source = ['#source/derived/filter_nonunique_push/get_unique_push.py']
for file in map(os.path.basename, glob.glob('../../../drive/output/scrape/push_pr_commit_data/pull_request_data/*.csv')):
    source.append(f'#drive/output/scrape/push_pr_commit_data/pull_request_data/{file}')
for file in map(os.path.basename, glob.glob('../../../drive/output/scrape/push_pr_commit_data/push_data/*.csv')):
    source.append(f'#drive/output/scrape/push_pr_commit_data/push_data/{file}')

env.Python(target, source)