Import('*')

"""
first in `pypi_monthly_downloads`, run
- query_monthly_pip_downloads.py
- get_popular_packages.py 
then in `pypi_site_info`, run
- get_library_json.sh
then in `extract_github_data`, run
- query_github_data.py
then in `push_pr_commit_data` run 
- get_pull_request_commits.py
- get_push_commits.py
then in `collect_commits` run
- get_commit_data_pr.py
- get_commit_data_push.py
"""


#SConscript('get_linkedin_profile/SConscript')

