Import('*')
import os
import glob

target = ['#drive/output/derived/repo_level_data/df_pr.parquet',
          '#drive/output/derived/repo_level_data/df_issue.parquet',
          '#drive/output/derived/repo_level_data/df_pr_commits.parquet',
          '#drive/output/derived/repo_level_data/df_push_commits.parquet']
source = ['#source/derived/repo_level_data/repo_level_data.py'] 
env.Precious(env.Python(target, source))
