Import('*')

from source.lib.helpers import LoadGlobalSettings, MakeRepoNameSafe

globals_data = LoadGlobalSettings("../../../source/lib/project_config.json")
reference_repo = globals_data['reference_github_repo']
reference_repo_safe_name = MakeRepoNameSafe(reference_repo)

source = [
    '#source/derived/create_bot_list/create_bot_list.py',
    f'#drive/output/scrape/extract_github_data/repo_level_data/issue/{reference_repo_safe_name}.parquet',
    f'#drive/output/scrape/extract_github_data/repo_level_data/pr/{reference_repo_safe_name}.parquet'
]

target = [
    '#output/derived/create_bot_list/bot_list.csv',
]

env.Python(target, source)
