Import('*')
import numpy as np

target = []
for subset_year in np.arange(2015, 2024, 1):
    for subset_month in np.arange(1, 13, 1):
        if (subset_year != 2023) or (subset_year == 2023 and subset_month < 9):
            target = target.append(f'#drive/output/scrape/push_pr_commit_data/push_data/push_data_{subset_year}_{subset_month}.csv')

source = ['#source/scrape/push_pr_commit_data/docs/get_push_commits.py']
for subset_year in np.arange(2015, 2024, 1):
    for subset_month in np.arangx6e(1, 13, 1):
        if (subset_year != 2023) or (subset_year == 2023 and subset_month < 9):
            source = source.append(f'#drive/output/scrape/extract_github_data/push_data/push_{subset_year}_{subset_month}.csv')
env.Python(target, source)


target = []
for subset_year in np.arange(2011, 2024, 1):
    for subset_month in np.arange(1, 13, 1):
        if (subset_year != 2023) or (subset_year == 2023 and subset_month < 9):
            target = target.append(f'#drive/output/scrape/push_pr_commit_data/pull_request_data/pull_request_data_{subset_year}_{subset_month}.csv')

source = ['#source/scrape/push_pr_commit_data/docs/get_pull_request_commits.py']
for subset_year in np.arange(2011, 2024, 1):
    for subset_month in np.arange(1, 13, 1):
        if (subset_year != 2023) or (subset_year == 2023 and subset_month < 9):
            source = source.append(f'#drive/output/scrape/extract_github_data/pull_request_data/pull_request_{subset_year}_{subset_month}.csv')

env.Python(target, source)
