Import('*')

from source.lib.helpers import LoadGlobalSettings, LoadPipelineInputs, MakeRepoNameSafe

_g      = LoadGlobalSettings("../../../source/lib/project_config.json")
_cfg    = LoadPipelineInputs("../../../source/lib/project_config.json")
ref     = MakeRepoNameSafe(_g['reference_github_repo'])
rolling = f"rolling{_g['rolling_periods']}"

importance_types = _cfg["importance_types"]["run"] + _cfg["importance_types"]["extended"]
rolling_periods  = [f"rolling{p}" for p in _cfg["rolling_periods"]["run"] + _cfg["rolling_periods"]["extended"]]
imp_members      = f'#output/derived/graph_structure/important_members/{ref}.csv'
bot_list         = '#output/derived/create_bot_list/bot_list.csv'

env.Python(
    target=[
        f'#drive/output/derived/org_outcomes_practices/org_outcomes/{ref}.parquet',
    ],
    source=[
        '#source/derived/org_outcomes_practices/org_outcomes.py',
        f'#drive/output/derived/action_data/repo_actions/{ref}.parquet',
        '#drive/output/scrape/pypi_downloads/pypi_monthly_downloads.parquet',
        '#output/scrape/pypi_site_info/linked_pypi_github.csv',
        '#output/scrape/extract_github_data/repo_id_history_final.csv',
    ],
)

env.Python(
    target=[
        f'#drive/output/derived/org_outcomes_practices/repo_collaboration/all/{rolling}/{ref}.parquet',
    ] + [
        f'#drive/output/derived/org_outcomes_practices/repo_collaboration/{imp}/{rolling}/{ref}.parquet'
        for imp in importance_types
    ],
    source=[
        '#source/derived/org_outcomes_practices/collaboration.py',
        f'#drive/output/derived/action_data/repo_actions/{ref}.parquet',
        f'#drive/output/derived/graph_structure/interactions/{ref}.parquet',
        imp_members,
        bot_list,
    ],
)

env.Python(
    target=[
        f'#drive/output/derived/org_outcomes_practices/repo_shared_knowledge/all/{rolling}/{ref}.parquet',
    ] + [
        f'#drive/output/derived/org_outcomes_practices/repo_shared_knowledge/{imp}/{rolling}/{ref}.parquet'
        for imp in importance_types
    ],
    source=[
        '#source/derived/org_outcomes_practices/shared_knowledge.py',
        f'#drive/output/derived/action_data/repo_actions/{ref}.parquet',
        imp_members,
        bot_list,
    ],
)

env.Python(
    target=[
        f'#drive/output/derived/org_outcomes_practices/repo_discussion_quality/all/{rolling}/{ref}.parquet',
    ] + [
        f'#drive/output/derived/org_outcomes_practices/repo_discussion_quality/{imp}/{rolling}/{ref}.parquet'
        for imp in importance_types
    ],
    source=[
        '#source/derived/org_outcomes_practices/discussion_quality.py',
        f'#drive/output/derived/action_data/repo_actions/{ref}.parquet',
        f'#drive/output/derived/graph_structure/interactions/{ref}.parquet',
        f'#drive/output/derived/action_data/cleaned_text/{ref}.parquet',
        imp_members,
        bot_list,
    ],
)

env.Python(
    target=[
        f'#drive/output/derived/org_outcomes_practices/repo_investment_in_new_talent/all/{rolling}/{ref}.parquet',
    ] + [
        f'#drive/output/derived/org_outcomes_practices/repo_investment_in_new_talent/{imp}/{rolling}/{ref}.parquet'
        for imp in importance_types
    ],
    source=[
        '#source/derived/org_outcomes_practices/investment_in_new_talent.py',
        f'#drive/output/derived/action_data/repo_actions/{ref}.parquet',
        f'#drive/output/derived/graph_structure/interactions/{ref}.parquet',
        f'#drive/output/scrape/governance_data/{ref}.parquet',
        imp_members,
        bot_list,
    ],
)

env.Python(
    target=[
        f'#drive/output/derived/org_outcomes_practices/repo_organizational_routines/{rolling}/{ref}.parquet',
    ],
    source=[
        '#source/derived/org_outcomes_practices/organizational_routines.py',
        f'#drive/output/derived/action_data/repo_actions/{ref}.parquet',
        f'#drive/output/scrape/governance_data/{ref}.parquet',
    ],
)

panel_targets = []
panel_sources = [
    '#source/derived/org_outcomes_practices/org_panel.py',
    '#source/lib/project_config.json',
    f'#drive/output/derived/org_outcomes_practices/org_outcomes/{ref}.parquet',
    imp_members,
]

for rolling_period in rolling_periods:
    panel_sources.extend([
        f'#drive/output/derived/org_outcomes_practices/repo_collaboration/all/{rolling_period}/{ref}.parquet',
        f'#drive/output/derived/org_outcomes_practices/repo_shared_knowledge/all/{rolling_period}/{ref}.parquet',
        f'#drive/output/derived/org_outcomes_practices/repo_discussion_quality/all/{rolling_period}/{ref}.parquet',
        f'#drive/output/derived/org_outcomes_practices/repo_investment_in_new_talent/all/{rolling_period}/{ref}.parquet',
        f'#drive/output/derived/org_outcomes_practices/repo_organizational_routines/{rolling_period}/{ref}.parquet',
    ])
    for importance_type in importance_types:
        panel_targets.extend([
            f'#drive/output/derived/org_outcomes_practices/org_panel/{importance_type}/{rolling_period}/panel.parquet',
            f'#output/derived/org_outcomes_practices/org_panel_{importance_type}_{rolling_period}.log',
        ])
        panel_sources.extend([
            f'#drive/output/derived/org_outcomes_practices/repo_collaboration/{importance_type}/{rolling_period}/{ref}.parquet',
            f'#drive/output/derived/org_outcomes_practices/repo_shared_knowledge/{importance_type}/{rolling_period}/{ref}.parquet',
            f'#drive/output/derived/org_outcomes_practices/repo_discussion_quality/{importance_type}/{rolling_period}/{ref}.parquet',
            f'#drive/output/derived/org_outcomes_practices/repo_investment_in_new_talent/{importance_type}/{rolling_period}/{ref}.parquet',
        ])

env.Python(panel_targets, panel_sources)
