Import('*')
import os
import glob

target = ['#drive/output/derived/problem_level_data/df_pr.parquet',
          '#drive/output/derived/problem_level_data/df_issue.parquet',
          '#drive/output/derived/problem_level_data/df_pr_commits.parquet',
          '#drive/output/derived/problem_level_data/df_push_commits.parquet']
source = ['#source/derived/problem_level_data/problem_level_data.py'] 
env.Precious(env.Python(target, source))


# sequential run order
# source/derived/problem_level_data/data_export.py
# source/derived/problem_level_data/combine_action_data.py
# source/derived/problem_level_data/clean_text.py
# source/derived/problem_level_data/text_variance.py