Import('*')
import os


autofill_sources = [
    '#output/autofill/event_study_autofill.tex',
    '#output/autofill/forest_autofill.tex',
    '#output/autofill/panel_autofill.tex',
    '#output/autofill/config_autofill.tex',
    '#output/autofill/pc_autofill.tex',
]

target = ['#output/paper/main.pdf']
source = ['#source/paper/main.tex', '#source/paper/references.bib'] + autofill_sources
env.Latex(target, source)


target = ['#output/paper/model.pdf']
source = ['#source/paper/model.tex']
env.Latex(target, source)
