Import('*')

target = ['#drive/source/scrape/pypi_monthly_downloads/orig/pypi_monthly_downloads.csv']
source = ['#source/scrape/pypi_monthly_downloads/docs/query_monthly_pip_downloads.py']

env.Python(target, source)

target = ['#source/scrape/pypi_monthly_downloads/data/popular_python_packages.csv']
source = ['#source/scrape/pypi_monthly_downloads/docs/get_popular_packages.py',
          '#drive/output/scrape/pypi_monthly_downloads/pypi_monthly_downloads.csv']

env.Python(target, source)
