Import('*')

from source.lib.helpers import LoadGlobalSettings, MakeRepoNameSafe

globals_data = LoadGlobalSettings("../../../source/lib/project_config.json")
reference_repo = globals_data['reference_github_repo']
reference_repo_safe_name = MakeRepoNameSafe(reference_repo)

combine_source = [
    '#source/derived/action_data/combine_action_data.py',
    f'#drive/output/scrape/extract_github_data/repo_level_data/issue/{reference_repo_safe_name}.parquet',
    f'#drive/output/scrape/extract_github_data/repo_level_data/pr/{reference_repo_safe_name}.parquet',
    f'#drive/output/scrape/link_issue_pull_request/linked_pull_request_to_issue/{reference_repo_safe_name}.parquet',
]
combine_target = [
    f'#drive/output/derived/action_data/repo_actions/{reference_repo_safe_name}.parquet',
    '#output/derived/action_data/dropped_stats.csv',
    '#output/derived/action_data/repo_component_tracking.csv',
]
env.Python(combine_target, combine_source)


clean_source = [
    '#source/derived/action_data/clean_text.py',
    f'#drive/output/derived/action_data/repo_actions/{reference_repo_safe_name}.parquet',
]
clean_target = [
    f'#drive/output/derived/action_data/cleaned_text/{reference_repo_safe_name}.parquet',
]
env.Python(clean_target, clean_source)
