Import('*')

SConscript('action_data/SConscript')
SConscript('analysis_panel/SConscript')
SConscript('create_bot_list/SConscript')
SConscript('graph_structure/SConscript')
SConscript('org_outcomes_practices/SConscript')
SConscript('model_prediction/SConscript')
