Import('*')

SConscript('collect_github_repos/SConscript')
SConscript('filter_nonunique_push/SConscript')
SConscript('data_export/SConscript')
SConscript('major_contributor_prospects/SConscript')
SConscript('project_outcomes/SConscript')