Import('*')
import pandas as pd

# Define source files and input dependencies
source = [
    'source/analysis/linkedin_departure_validation/linkedin_departure_validation.py',
    'drive/output/scrape/get_standardized_locations/standardized_locations_github.csv',
    'drive/output/scrape/get_standardized_locations/standardized_locations_linkedin.csv',
    'drive/output/scrape/get_linkedin_profiles/departed_github_profiles.csv',
    'drive/output/scrape/get_linkedin_profiles/departed_linkedin_profiles.parquet',
    'drive/output/scrape/get_linkedin_profiles/departed_linkedin_positions.parquet',
]
target = ['drive/output/analysis/linkedin_departure_validation/linkedin_validation_stats.csv']

indir_departed = "drive/output/derived/contributor_stats/departed_contributors"
outdir_es = 'output/analysis/linkedin_departure_validation/event_studies'

for time_period in [2, 3, 6]:
    for rolling_window in [732, 1828]:
        spec_summary_file = f'{indir_departed}/departed_contributors_specification_summary_major_months{time_period}_window{rolling_window}D.csv'
        df_specifications = pd.read_csv(spec_summary_file).query('criteria_col == "commits"')
        source.append(spec_summary_file)
        for spec_idx in df_specifications.index:
            spec = df_specifications.loc[spec_idx]
            criteria_pct, consecutive_periods = spec['criteria_pct'], spec['consecutive_periods']
            post_period_length, decline_type, decline_stat = spec['post_period_length'], spec['decline_type'], spec['decline_stat']
            decline_stat = int(decline_stat) if decline_stat == 0 or decline_type == "threshold_gap_qty" else decline_stat
            departed_file = f'{indir_departed}/departed_contributors_major_months{time_period}_window{rolling_window}D_criteria_commits_{criteria_pct}pct_consecutive{consecutive_periods}_post_period{post_period_length}_{decline_type}_{decline_stat}.parquet'
            source.append(departed_file)

            filename = f"{outdir_es}/event_study_major_months{time_period}_window{rolling_window}D_criteria_commits{criteria_pct}_consec{consecutive_periods}_post{post_period_length}_{decline_type}_{decline_stat}.png"
            target.append(filename)

env.Python(target, source)  
