Import('*')
import os
import glob

target = ['#drive/output/derived/data_export/df_pr.parquet',
          '#drive/output/derived/data_export/df_issue.parquet',
          '#drive/output/derived/data_export/df_pr_commits.parquet',
          '#drive/output/derived/data_export/df_push_commits.parquet']
source = ['#source/derived/data_export/data_export.py'] 
env.Precious(env.Python(target, source))
