Import('*')

source = [
    '#source/derived/graph_structure/create_graphs.py',
    '#output/derived/hashes/repo_actions.txt',
]
target = [
    '#output/derived/hashes/interactions.txt',
    '#output/derived/graph_structure/exported_graphs_log.csv',
]
env.Python(target, source)

source = [
    '#source/derived/graph_structure/calculate_degree.py',
    '#output/derived/hashes/interactions.txt',
]
target = [
    '#output/derived/hashes/graph_degrees.txt',
]
env.Python(target, source)

source = [
    '#source/derived/graph_structure/calculate_importance.py',
    '#source/lib/config/importance_specifications.json',
    '#output/derived/hashes/graph_degrees.txt',
    '#output/derived/hashes/repo_actions.txt',
]
target = [
    '#output/derived/hashes/important_members.txt',
    '#output/derived/graph_structure/importance_summary.csv',
]
env.Python(target, source)
