Import('*')
import os
import glob
import pandas as pd
import numpy as np


time_period_months = [2, 3, 6]
rolling_window_list = [732, 1828]
comment_col = 'comments'
issue_col = 'issue_comments'
commit_col = 'commits'
criteria_col_list = [comment_col, issue_col, commit_col]  
criteria_pct_list = [75, 90]
consecutive_periods_major_months_dict = {2: [3, 9, 18],
                                         3: [3, 6, 12],
                                         6: [3, 6]}

post_periods_major_months_dict = {2: [3, 6, 12],
                                3: [2, 4, 8],
                                6: [2, 4]}

decline_type_list = ['threshold_mean', 'threshold_gap_qty'] #['threshold_mean','threshold_pct']
decline_threshold_list = [0.2, 0.1, 0]
decline_gap_qty_list = [0, 5]



for time_period in time_period_months:
    source = ['#source/derived/project_outcomes/generate_project_outcomes.py', 
        '#drive/output/derived/data_export/df_issue.parquet', 
        '#drive/output/derived/data_export/df_pr.parquet',
        f'#drive/output/derived/contributor_stats/contributor_data/major_contributors_major_months{time_period}_window732D_samplefull.parquet']
    target = [f'#drive/output/derived/project_outcomes/project_outcomes_major_months{time_period}.parquet']
    env.Precious(env.Python(target, source, CL_ARG = f"{time_period}"))


outdir = 'drive/output/derived/project_outcomes'
rolling_window = 732
indir = 'drive/output/derived/contributor_stats/contributor_data'

for time_period in time_period_months:
    target = [f'#{outdir}/project_covariates_major_months{time_period}.parquet',
        f'#{outdir}/contributor_covariates_major_months{time_period}.parquet']

    source = ["#source/derived/project_outcomes/generate_project_covariates.py",
        f'#{indir}/major_contributors_major_months{time_period}_window{rolling_window}D_samplefull.parquet']
    env.Precious(env.Python(target, source, CL_ARG = f"{time_period}"))


consecutive_periods_list = np.arange(2, 5, 1)
permanent_departure_options = [True, False]
time_period = 6
rolling_window = 732

target = []
for consecutive_periods in consecutive_periods_list:
    for permanent_departure in permanent_departure_options:
        outdir = "drive/output/derived/project_outcomes/abandoned_projects"
        target.append(f"#{outdir}/abandoned_projects_consecutive_req{consecutive_periods}_permanent{str(permanent_departure)}.parquet")
target.append(f'#{outdir}/abandoned_projects_specifications.csv')
indir = "drive/output/derived/contributor_stats/contributor_data"
source = ["#source/derived/project_outcomes/identify_abandoned_projects_activity.py",
    f'#{indir}/major_contributors_major_months{time_period}_window{rolling_window}D_samplefull.parquet']
env.Precious(env.Python(target, source))


outdir = 'drive/output/derived/project_outcomes/abandoned_projects'
target = [f'#{outdir}/scraped_abandoned_repo_data.csv']
indir = 'drive/output/derived/contributor_stats/contributor_data'
time_period = 6
rolling_window = 732
source = ["#source/derived/project_outcomes/identify_abandoned_projects_scraper.py",
    f'#{indir}/major_contributors_major_months{time_period}_window{rolling_window}D_samplefull.parquet']
env.Precious(env.Python(target, source))


