name: Github Actions CI to build pdf from tex source.
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@3.2.0
      with:
          # The root LaTeX file to be compiled
          root_file: source/paper/main.tex
      
    - name: Upload PDF file
      uses: actions/upload-artifact@v4
      with:
          name: PDF
          path: output/paper/main.pdf

    - name: Upload file to repository
      run: |
        git config --global user.name "liaochris"
        git config --global user.email "liaochris@users.noreply.github.com"
        git add output/paper/main.pdf
        git commit -m "compiling pdf skip ci"
        git push
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
