name: Github Actions CI to build pdf from tex source.
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile Introduction and Model
      uses: xu-cheng/latex-action@3.2.0
      with:
          # The root LaTeX file to be compiled
          root_file: source/paper/sections/introduction.tex  source/paper/sections/model.tex source/paper/sections/method.tex source/paper/main.tex source/paper/external/utility_theory.tex

    - name: Move Components
      run: |
        mkdir -p output/paper/sections/
        mkdir -p output/paper/external/
        mv introduction.pdf output/paper/sections/introduction.pdf
        mv model.pdf output/paper/sections/model.pdf
        mv model.pdf output/paper/sections/method.pdf
        mv main.pdf output/paper/main.pdf     
        mv utility_theory.pdf output/paper/external/utility_theory.pdf

    - name: Commit compiled PDFs
      run: |
        git add *.pdf
        git config --local user.email "liaochris"
        git config --local user.name "liaochris@users.noreply.github.com"
        git commit -m "moving pdf skip ci"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

        
