name: Github Actions CI to build pdf from tex source.
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile Paper
      uses: xu-cheng/latex-action@3.2.0
      with:
          # The root LaTeX file to be compiled
          root_file: source/paper/main.tex
          
    - name: Compile Introduction
      uses: xu-cheng/latex-action@3.2.0
      with:
          # The root LaTeX file to be compiled
          root_file: source/paper/introduction.tex 

    - name: Compile Model
      uses: xu-cheng/latex-action@3.2.0
      with:
          # The root LaTeX file to be compiled
          root_file: source/paper/model.tex 
      
    - name: Upload introduction and paper
      run: |
        git config --global user.name "liaochris"
        git config --global user.email "liaochris@users.noreply.github.com"
        git add main.pdf introduction.pdf model.pdf
        git commit -m "compiling pdf skip ci"

    - name: Move introduction and paper
      run: |
        mv main.pdf output/paper/main.pdf
        mv introduction.pdf output/paper/sections/introduction.pdf
        mv model.pdf output/paper/sections/introduction.pdf
        
    - name: Update pdf locations
      run: |
        git add *main.pdf *introduction.pdf *model.pdf
        git config --local user.email "liaochris"
        git config --local user.name "liaochris@users.noreply.github.com"
        git commit -m "moving pdf skip ci"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
