name: Github Actions CI to build pdf from tex source.
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile Introduction and Model
      uses: xu-cheng/latex-action@3.2.0
      with:
          # The root LaTeX file to be compiled
          root_file: source/paper/sections/introduction.tex  source/paper/sections/model.tex 

    - name: Move Introduction and Model
      run: |
        mv *.pdf output/paper/sections/
      
    - name: Compile Paper
      uses: xu-cheng/latex-action@3.2.0
      with:
          # The root LaTeX file to be compiled
          root_file: source/paper/main.tex
          
    - name: Move Paper
      run: |
        mv *.pdf output/paper/sections/     

    - name: Commit compiled PDFs
      run: |
        git add *.pdf
        git config --local user.email "liaochris"
        git config --local user.name "liaochris@users.noreply.github.com"
        git commit -m "moving pdf skip ci"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
