name: LateX to PDF

on:
  push:
    branches: 
      - main
    tags:
       - '*'
  pull_request:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: latex2pdf
        id: compile-latex-document
        uses: thomas-chauvet/latex2pdf-action@1.1.0
        with:
          output_dir: output/paper
          main_latex_file: source/paper/main.tex
          ctan_packages: amsfonts lua-uni-algos amssymb amsmath graphicx epstopdf pdflscape tabularx longtable array dsfont float booktabs tikz marvosym multirow pdflscape url setspace epigraph bm textcomp diagbox bbm verbatim mdframed subcaption caption lipsum mathtools scalerel stackengine amsthm hyperref hyperref epsfig biblatex enumitem
      - name: Upload PDF to the workflow tab
        id: upload-workflow-tab
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output/paper/main.pdf
